### ISSUE TITLE
ItemMeta of ItemStacks is not properly set

### ISSUE THREAD

**Issue by bibo38** [Cube-Space/Yamler#24]
In the [ItemStack.java](https://github.com/Cube-Space/Yamler/blob/27a28f1967d4d5cfaaa09c3d1760a65fb8a0570a/Yamler-Bukkit/src/main/java/net/cubespace/Yamler/Converter/ItemStack.java#L56) converter the ItemMeta is not properly set.
The getItemMeta() method only returns a clone of the actual ItemMeta, so that the ItemMeta must be set again after change like this:
```java
ItemMeta meta = itemStack.getItemMeta();
meta.set...
itemStack.setItemMeta(meta);
```

**Comment by bibo38** [comment]
Some rationale about the mass closing of issues would be nice...
E.g. **WHY** is this issue(and all other issues) closed?

**Comment by geNAZt** [comment]
These Issues have been closed since they are nearly one Year old and should be fixed by now. But i saw that this issue has not been fixed. I will do that now
