### ISSUE TITLE
Struggling with Yamler - Please Help!

### ISSUE THREAD

**Issue by GoadingGoat** [Cube-Space/Yamler#27]
Getting this error  (Which i don't find very helpful at all):
![error](https://cloud.githubusercontent.com/assets/11308755/14941478/ad114554-0ff1-11e6-9e38-c2be868d23b7.PNG)
May not have stuff set up quite correctly.
i have my main class:
![main](https://cloud.githubusercontent.com/assets/11308755/14941569/3ab7fd74-0ff4-11e6-9df6-f2aacd3c543f.PNG)
ConfigManager:
![configmanager](https://cloud.githubusercontent.com/assets/11308755/14941503/a31ae004-0ff2-11e6-962c-7a88246f0492.PNG)
and two config files(MainConfig and Messages):
![messages](https://cloud.githubusercontent.com/assets/11308755/14941519/faab860c-0ff2-11e6-8fff-3ca780c8485c.PNG)
![mainconfig](https://cloud.githubusercontent.com/assets/11308755/14941520/fcee262c-0ff2-11e6-832c-b486cdc79c9b.PNG)

It's not creating a folder with the configs in it. I'm rather stumped as to what I've done wrong. Please Help!

**Comment by geNAZt** [comment]
Seems like you did not shade or depend on Yamler correctly

**Comment by GoadingGoat** [comment]
i have this for my pom.xml (renamed to txt so github would accept it):

[pom.txt](https://github.com/Cube-Space/Yamler/files/244104/pom.txt)

Is there something i need to change or add in it?

**Comment by geNAZt** [comment]
You don't shade the JAR. Did you throw the Yamler Bukkit Plugin into your Plugins Folder?

**Comment by GoadingGoat** [comment]
no, i haven't downloaded them, they were supposed to be download from http://maven.addstar.com.au/artifactory/ext-snapshot-local/ and maven would build them, but the repo appears to be out of date. Is there another repo i could use? or should i get the jar files from jenkins?

**Comment by GoadingGoat** [comment]
Ok, Putting the Yamler-Bukkit.jar in my plugins folder fixed the error. Thanks
